version: '3.8'
services:
  ylab-project:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=nikguscode
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ylabdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"